config/routes.rb
Kitchen::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

resources :recipes

resources :categories

resources :notes

 resources :jobs

 resources :statuses

resources :ratings

   resources :search

 resources :recipes, :has_many => :comments

end

app/models/notes.rb
class Notes < ActiveRecord::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.xml
  def index
    @notes = Notes.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @notes = Notes.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @notes = Notes.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1/edit
  def edit
    @notes = Notes.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @notes = Notes.new(params[:notes])

    respond_to do |format|
      if @notes.save
        flash[:notice] = 'Notes was successfully created.'
        format.html { redirect_to(@notes) }
        format.xml  { render :xml => @notes, :status => :created, :location => @notes }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @notes.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @notes = Notes.find(params[:id])

    respond_to do |format|
      if @notes.update_attributes(params[:notes])
        flash[:notice] = 'Notes was successfully updated.'
        format.html { redirect_to(@notes) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @notes.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @notes = Notes.find(params[:id])
    @notes.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/edit.html.erb
<h1>Editing notes</h1>

<%= error_messages_for :notes %>

<% form_for(@notes) do |f| %>
  <p>
    <b>Comment</b><br />
    <%= f.text_area :comment %>
  </p>

  <p>
    <b>Job</b><br />
    <%= f.text_field :job %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @notes %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Job</th>
  </tr>

<% for notes in @notes %>
  <tr>
    <td><%=h notes.comment %></td>
    <td><%=h notes.job %></td>
    <td><%= link_to 'Show', notes %></td>
    <td><%= link_to 'Edit', edit_notes_path(notes) %></td>
    <td><%= link_to 'Destroy', notes, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New notes', new_notes_path %>

app/views/notes/new.html.erb
<h1>New notes</h1>

<%= error_messages_for :notes %>

<% form_for(@notes) do |f| %>
  <p>
    <b>Comment</b><br />
    <%= f.text_area :comment %>
  </p>

  <p>
    <b>Job</b><br />
    <%= f.text_field :job %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p>
  <b>Comment:</b>
  <%=h @notes.comment %>
</p>

<p>
  <b>Job:</b>
  <%=h @notes.job %>
</p>


<%= link_to 'Edit', edit_notes_path(@notes) %> |
<%= link_to 'Back', notes_path %>