config/routes.rb
Kitchen::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

resources :recipes

resources :categories

resources :notes

 resources :jobs

 resources :statuses

resources :ratings

   resources :search

 resources :recipes, :has_many => :comments

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :comments 
acts_as_rateable
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  protect_from_forgery :only => [:update, :delete, :create]
  # auto_complete_for :title, :description
  # GET /recipes
  # GET /recipes.xml
  def index
    @recipes = Recipe.find(:all)
    
    unless params[:recipeSearch].nil?
      @recipe = Recipe.find_by_title(params[:recipeSearch][:description])
      #params[:recipe][:description] = ''
      redirect_to :controller=>"recipes", :action=>:show, :id=>@recipe
      
    else
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @recipes }
      end
    end
  end
  
  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end
  
  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end
  
  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new(params[:recipe])
    
    respond_to do |format|
      if @recipe.save
        flash[:notice] = 'Recipe was successfully created.'
        format.html { redirect_to(@recipe) }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])
    
    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        flash[:notice] = 'Recipe was successfully updated.'
        format.html { redirect_to(@recipe) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    
    respond_to do |format|
      format.html { redirect_to(recipes_url) }
      format.xml  { head :ok }
    end
  end
 
 def search
    
    unless params[:recipeSearch].nil?
      @recipe = Recipe.find_by_title(params[:recipeSearch][:description])
      #params[:recipe][:description] = ''
      unless @recipe.nil?
        redirect_to :controller=>"recipes", :action=>"show", :id=>@recipe
        
      else
        flash[:notice] = "No recipes found, try the list instead"
        redirect_to :controller=>"recipes", :action=>"index"

      end
    else
      @recipes = Recipe.find(:all)
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @recipes }
        redirect_to :controller=>"recipes", :action=>"index"
      end
      
    end
  end
 
  # def auto_complete_for_recipe_description
  #search = params[:recipe][:description]
  #recipes = Recipe.search(search) unless search.blank?
  #render :partial => "live/search" 
  #end
  def auto_complete_for_recipeSearch_description
    criteria = '%' + params[:recipeSearch][:description] + '%'
    @recipes = Recipe.find(:all, 
                           :conditions=>["title like ? OR description like ?",criteria, criteria],
    :order=>'title desc', :limit=>10)
    render :partial=> "recipes" 
  end
  
 
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_menu.html.erb
<div id="headerCell"><%= link_to  'New Recipe', { :action => 'new', :controller => :recipes } %></td></div>
<div id="headerCell"><%= link_to  'List Recipes', { :action => 'index', :controller => :recipes } %></td></div>
<div id="searchCell">
 % form_for :recipe, :url=>{ :controller => :recipes, :action => 'search' } do |form| %>
   < text_field_with_auto_complete :recipeSearch, :description > 
    <%= submit_tag "Search" %>
% end %>
</div>
	

app/views/recipes/_recipeForm.html.erb
<% form_for(@recipe) do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <b>Description</b><br />
   
	 <%= fckeditor_textarea( :recipe, :description, :height => '420' ) %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

app/views/recipes/_recipes.html.erb
<ul>
    <% @recipes.each do |recipe| %>
        <li><%= recipe.title%></li>
    <% end %>
</ul>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= error_messages_for :recipe %>

<%= render :partial => 'recipeForm' %>
<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Title</th>
    
  </tr>

<% for recipe in @recipes %>
  <tr>
    <td><%=h recipe.title %></td>
    
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= error_messages_for :recipe %>

<%= render :partial => 'recipeForm' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%= link_to 'Edit', { :action => 'edit', :id => @recipe } %>
<p>
	

  <h1><%=h @recipe.title %></h1>
</p>

<p>
  <b>Description:</b>
  <%= @recipe.description %>
</p>

<%= render :partial => "ratings/rate",  :locals => { :recipe => @recipe } %>

<% unless @recipe.comments.empty? %>
  <h3>Comments</h3>
  <% @recipe.comments.each do |comment| %>
  <hr>
  Posted on <%= h comment.created_at%> <%= link_to 'Edit', edit_recipe_comment_path( @recipe, comment ) %>
  <p><%=  comment.description %></p>
  
  <% end %>
<% end %>

<!-- #2 -->
<h3>New Comment</h3>
<%= render :partial => @comment = Comment.new, 
   :locals => { :button_name => 'Create'}%>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>