config/routes.rb
Kitchen::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

resources :recipes

resources :categories

resources :notes

 resources :jobs

 resources :statuses

resources :ratings

   resources :search

 resources :recipes, :has_many => :comments

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :recipe
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.find(:all)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end
  
  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = Rating.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end
  
  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = Rating.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end
  
  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end
  
  # POST /ratings
  # POST /ratings.xml
  def create
    @rating = Rating.new(params[:rating])
    
    respond_to do |format|
      if @rating.save
        flash[:notice] = 'Rating was successfully created.'
        format.html { redirect_to(@rating) }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = Rating.find(params[:id])
    
    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        flash[:notice] = 'Rating was successfully updated.'
        format.html { redirect_to(@rating) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    
    respond_to do |format|
      format.html { redirect_to(ratings_url) }
      format.xml  { head :ok }
    end
  end
  
  # Rating method
  def rate
    id = 10
    @recipe = Recipe.find(params[:id])
    Rating.delete_all(["rateable_type = 'Recipe' AND rateable_id = ? AND user_id = ?",
    @recipe.id, id])
    @recipe.add_rating Rating.new(:rating => params[:rating],
                                  :user_id => id)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_rate.html.erb
<%= number_with_precision(recipe.rating, 1) %>/5 Stars
</p>
	<ul class='star-rating'>
    <li class''current-rating' style='width:<%= (recipe.rating * 30).to_i -%>px;'> 
        Currently 
        <%= number_with_precision(recipe.rating, 1) %>/5 Stars. 
    </li>

	<br>
	<br>
    <li>
        <%= link_to_remote( "1", {:url => { :controller => "ratings",
        :action => "rate", :id => recipe.id, :rating => 1}},
        :class => 'one-star', :name => '1 star out of 5') %>
    </li>
    <li>
        <%= link_to_remote( "2", {:url => { :controller => "ratings",
        :action => "rate", :id => recipe.id, :rating => 2}},
        :class => 'two-stars', :name => '2 stars out of 5') %>
    </li>
    <li>
        <%= link_to_remote( "3", {:url => { :controller => "ratings",
        :action => "rate", :id => recipe.id, :rating => 3}},
        :class => 'three-stars', :name => '3 stars out of 5') %>
    </li>
    <li>
        <%= link_to_remote( "4", {:url => { :controller => "ratings",
        :action => "rate", :id => recipe.id, :rating => 4}},
        :class => 'four-stars', :name => '4 stars out of 5') %>
    </li>
    <li>
        <%= link_to_remote( "5", {:url => { :controller => "ratings",
        :action => "rate", :id => recipe.id, :rating => 5}},
        :class => 'five-stars', :name => '5 stars out of 5') %>
    </li>
	
</ul>
<p>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= error_messages_for :rating %>

<% form_for(@rating) do |f| %>
  <p>
    <b>Value</b><br />
    <%= f.text_field :value %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Value</th>
  </tr>

<% for rating in @ratings %>
  <tr>
    <td><%=h rating.value %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= error_messages_for :rating %>

<% form_for(@rating) do |f| %>
  <p>
    <b>Value</b><br />
    <%= f.text_field :value %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p>
  <b>Value:</b>
  <%=h @rating.value %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>